<h2>Add Product</h2>
<br>
<?php echo $this->tag->form("product/add"); ?>
    <label for="name">Name:
        <input type="text" name="name" id="name">
    </label><br><br>
    <label for="description">Description:
        <textarea name="description" id="description" cols="30" rows="3"></textarea>
    </label><br><br>
    <label for="tags">Tags:
        <input type="text" name="tags" id="tags">
    </label><br><br>
    <label for="price">Price:
        <input type="text" name="price" id="price">
    </label><br><br>
    <label for="stock">Stock:
        <input type="text" name="stock" id="stock">
    </label><br><br>
    <input class="btn btn-primary" type="submit" value="Add">
</form>
<br>
<?php
echo $this->tag->linkTo([
    'product',
    'Back',
    'class' => 'btn btn-primary'
]);