<h2>Display Order</h2>
<table class="table table-borderd table-striped">
    <caption>Order Table</caption>
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Zipcode</th>
            <th>Product</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        <?php
        echo $display;
        ?>
    </tbody>
</table>

<?php

echo PHP_EOL;

echo $this->tag->linkTo(['index','Back','class' => 'btn btn-primary mx-2']);

echo PHP_EOL;

echo $this->tag->linkTo([
    'order/list',
    'Order Add',
    'class' => 'btn btn-primary mx-2'
]);